on:
  push:
    branches: main
    tags:
      - v*
jobs:
  release_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JAVA 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: 17

      - name: Cache Gradle and wrapper
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

      #1
      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.GAZETTE_SIGNING_KEY_BASE64 }}
          GAZETTE_SIGNING_KEY: ${{ secrets.GAZETTE_SIGNING_KEY }}

        run: | 
          echo "$ENCODED_STRING" > keystore-base64.txt 
          base64 -d keystore-base64.txt > $GAZETTE_SIGNING_KEY


      - name: Make gradlew executable
        run: chmod +x ./gradlew

      #2
      - name: Build Release apk
        env:
          GAZETTE_SIGNING_KEY: ${{ secrets.GAZETTE_SIGNING_KEY }}
          GAZETTE_KEY_ALIAS: ${{ secrets.GAZETTE_KEY_ALIAS }}
          GAZETTE_KEYSTORE_PASSWORD: ${{ secrets.GAZETTE_KEYSTORE_PASSWORD }}
          GAZETTE_NYT_API_KEY: ${{ secrets.GAZETTE_NYT_API_KEY  }}
        run: |
          export GAZETTE_SIGNING_KEY=GazetteSigningKey.jks
          export GAZETTE_KEYSTORE_PASSWORD=${{ secrets.GAZETTE_KEYSTORE_PASSWORD }}
          export GAZETTE_KEY_ALIAS=${{ secrets.GAZETTE_KEY_ALIAS }}
          ./gradlew assembleRelease

      #3
      - name: Upload Release Build to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          paths: |
            app/build/outputs/apk/release/
            app/build/outputs/bundle/release/
      #4
      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          prerelease: true
          files: |
            app/build/outputs/apk/release/app-release.apk
